theme: jekyll-theme-cayman
# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

title: Carenin
description: "&quot;Carenin&quot; занимается созданием сайтов под ключ."
keywords: "Создание сайтов, разработка"

url: http://carenin.ru
baseurl: ""

author:
  name      : Fernando Moreira
  job       : Frontend Engineer
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  github    : http://github.com/nandomoreirame
  twitter   : http://twitter.com/nandomoreirame
  facebook  : http://facebook.com/fernando.dev
  linkedin  : http://linkedin.com/in/nandomoreirame